### ISSUE TITLE
[Ингредиенты] Разработка модели ингредиентов и программная реализация 

### ISSUE THREAD

**Issue by AlexandrSergei4** [ncedu-tlt/2018-eaters-club#3]
- [ ]  1. Придумать модель ингредиентов, основные поля ингредиентов

 Учесть:
- [ ] Ингредиенты должны иметь энергетическую ценность (кбжу)
- [x] У ингредиентов есть срок годности
- [x] Ингредиенты должны иметь систему тэгов

- [ ] 2. Написать Java CLI приложение с реализацией и использованием придуманной модели.

- [ ] В программе должно быть добавление редактирование и удаление ингредиентов, все ингредиенты хранить пока-что в памяти.

- [ ] Программа должны ументь получать список ингредиентов которые имеют наивысшую энергетическую ценность и при этом срок годности подходит к концу.

По итогу написанное  приложение закомитить себе в ветку.

Необязательно - описать модель в вики нашего репозитория здесь:
https://github.com/ncedu-tlt/2018-eaters-club/wiki

**Comment by vladjef** [comment]
https://github.com/ncedu-tlt/2018-eaters-club/tree/features/efremenko_module

**Comment by vladjef** [comment]
Alexander K., please review branch.

**Comment by AlexandrSergei4** [comment]
@vladjef Спасибо, код просмотрел

Замечания такие:

- Как я понял реализации выборки по продуктам которые надо сьесть нет, в том числе из за вопроса в #4, но это все равно должно быть.
- У модели должен быть метод toString для того чтобы в cli удобно выводить информацию о нем. Кроме того toString относится к методам которые рекомендуются к епреопределению у любого класса. 
![image](https://user-images.githubusercontent.com/5618856/49285877-22342980-f4b2-11e8-8c7d-c3827b0bcf14.png)
- В мейне слишком мало объектов создано для демонстрации, и не выводится вся информация об объекте.


Вопросы по имеющемуся коду такие:

1. Почему единица измерения и типы продукты сделаны через enum? Каким образом предполагается добавления типа продукта? 
2. Почему для тегов используется hashset?
3. Почему теги начинаются с символа "#"

**Comment by vladjef** [comment]
>>Почему единица измерения и типы продукты сделаны через enum? Каким образом предполагается добавления типа продукта?
Возможно, разделение ингредиентов по типам будет полезной при их добавлении в холодильник. Равносильно полкам в реальном холодильнике: замороженные продукты, овощи, все типы лежат отдельно.

>>Почему для тегов используется hashset?
Реализация: private Collection<String> tags = new HashSet<>(); // Tags of ingredient
Цель - создание тегов без дубликатов.

>> Почему теги начинаются с символа "#"
Поправил.

**Comment by AlexandrSergei4** [comment]
По этой задаче все.
Остались некоторые недостатки, считаем что будут исправлены в будущем если эти части кода пойдут дальше.
Недостатки такие:
 - Не учтено что пользователь может ввести неправильный айди при удалении или трате, в случае которого будет NPE;
 - Формулировка срок годности непонятна - имеется ввиду окончание?
 - Всегда вводится одинаковая размерность - g.
 - Можно добавить только один тэг при создании продукта;
 - Нельзя изменить данные внесенного продукт, можно только потратить.
 - Метод setTags непрвильно назван, т.к. добавляет только один тег, хотя называется setTags;
 - Неправильно реализована функция сравнения для калорий, работает наоборот. функция compare всегда должна быть реализована согласна регламенту;
 - Нет опции выхода;
